name: Deploy to preview

# Controls when a worklflow runs
on:
  push:
    branches: [development]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v2

      - name: "run: git config --local --get remote.origin.url"
        run: git config --local --get remote.origin.url

      - name: "Setup node version"
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          # cache: 'npm'

      - name: "Cache update"
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: "Cache npm packages"
        id: npmCacheStep
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: "Build site"
        if: steps.npmCacheStep.output.cache-hit != 'true'
        run: |
          npm install
          npm run test:ci

      - name: "Deploy to vercel"
        if: steps.npmCacheStep.output.cache-hit != 'true'
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          # github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
